version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  target-branch: "1.2.x"
  labels:
  - type/dependency-upgrade
  ignore:
  # Don't update Reactor projects
  - dependency-name: io.projectreactor:*
  - dependency-name: io.projectreactor.addons:*
  # JSR305 backport is fixed to last version with annotations (3.0.1)
  - dependency-name: "com.google.code.findbugs:jsr305"
  # artifactory: don't upgrade to v5
  - dependency-name: "com.jfrog.artifactory"
    versions:
    - ">= 5.0.a"
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
      interval: daily
  open-pull-requests-limit: 10
  assignees:
      - violetagg
  target-branch: "1.2.x"
  labels:
      - type/dependency-upgrade
  rebase-strategy: disabled
