name: CI
on:
  pull_request: {}
permissions: read-all
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
    - name: gradle
      run: ./gradlew check dokkaHtml dokkaJavadoc
