name: CI
on:
  pull_request: {}
permissions: {}
jobs:
  checks:
    name: checks
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
    - name: gradle
      run: ./gradlew check dokkaHtml dokkaJavadoc
