name: CI
on:
  pull_request: {}
permissions: read-all
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # renovate: tag=v2
      with:
        distribution: 'temurin'
        java-version: 8
    - uses: gradle/gradle-build-action@4c39dd82cd5e1ec7c6fa0173bb41b4b6bb3b86ff # renovate: tag=v2
      name: gradle
      with:
        arguments: check dokkaHtml dokkaJavadoc