name: "Gradle Wrapper"
on: [push, pull_request]
permissions: read-all

jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2 # renovate: tag=v1
