name: "Gradle Wrapper"
on: [push, pull_request]
permissions: {}

jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: gradle/actions/wrapper-validation@748248ddd2a24f49513d8f472f81c3a07d4d50e1
