name: "Gradle Wrapper"
on: [push, pull_request]
permissions: read-all

jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # renovate: tag=v1
