name: "Gradle Wrapper"
on: [push, pull_request]
permissions: read-all

jobs:
  validation:
    name: "validation"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: gradle/actions/wrapper-validation@8379f6a1328ee0e06e2bb424dadb7b159856a326
